# Generated by Django 4.2 on 2023-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
