# Generated by Django 4.2 on 2023-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
