# Generated by Django 4.2 on 2023-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_product_id_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
