# Generated by Django 4.2 on 2023-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_order_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentstatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pendingamount',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
