# Generated by Django 4.2 on 2023-06-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expireDate',
        ),
    ]
