# Generated by Django 4.2 on 2023-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_product_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.AutoField(default=10000, primary_key=True, serialize=False),
        ),
    ]
