# Generated by Django 4.2 on 2023-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='productNo',
            field=models.AutoField(default=362023, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
